automl/SMAC3

smac/scenario/scenario.py, smac/smbo/smbo.py, smac/tae/execute_func.py, smac/tae/execute_ta_run.py, test/test_smbo/test_smbo.py, test/test_tae/test_exec_func.py, test/test_tae/test_execute_ta_run.py
1. limit wallclock time instead of cpu time. I was not able to write
a unit test which limits cpu time, and I don't see a reason why
one would only want to limit cpu time
2. allow to enforce a memory limit
3. consider the algorithm run to have failed if the return value is
None
4. add unittests
=> FIX #46, also fixes the following issues:

smac/facade/smac_facade.py, smac/intensification/intensification.py
This PR replaces the use of np.random, which is not seeded, with self.rng, the SMAC-global random number generator. This should make SMAC deterministic (given that the algorithms always take the same amount of time;)).
=> FIX #62, replace random with self.rng in intensification.py

smac/runhistory/runhistory.py, smac/smbo/objective.py, test/test_smbo/test_pSMAC.py
This PR makes the runhistory pickleable by moving private classes out of the runhistory class.
=> ENH # 42, make runhistory pickleable

smac/scenario/scenario.py, test/test_runhistory/test_runhistory2epm.py, test/test_scenario/test_scenario.py, test/test_tae/test_exec_func.py, test/test_tae/test_execute_ta_run.py, test/test_tae/test_tae_aclib.py, test/test_tae/test_tae_old.py, test/test_utils/io/test_traj_logging.py
This PR makes sure that either the argument `cs` or `paramfile` is passed to the scenario object.
=> FIX #72, config space now mandatory for scenario

smac/facade/roar_facade.py, smac/facade/smac_facade.py, test/test_facade/test_smac_facade.py
Allows passing a callable to the SMAC or ROAR class. The SMAC class will then wrap the callable in the necessary ExecuteTaRun class. Fixes #49
=> ADD allow passing callable as target algorithm

examples/rosenbrock.py
This PR replaces the 4d rosenbrock example by a 2d rosenbrock example, fixes #79.
=> MAINT replace rosenbrock 4d by rosenbrock 2d

smac/runhistory/runhistory.py, test/test_runhistory/test_runhistory.py
This PR adds a unit test to ensure that the runhistory (with simple data) can be pickled.
=> MAINT extend runhistory unit test for picklability

.travis.yml, requirements.txt, setup.py
This PR does:
* increase version number of scipy and numpy dependency
* only use requirements.txt, remove dependencies from setup.py
* set up environment for successful MAC OS builds
* use anaconda gcc instead of ubuntu gcc for compilation on travis-ci (side-effect, MAC OS build works)
=> update travis-ci, use requirements.txt

MANIFEST.in
Adding the manifest adds the requirements to the SMAC source distribution file. This is crucial as the setup.py reads the requirements file.
=> MAINT add MANIFEST.in to allow pip install smac.tar.gz

smac/scenario/scenario.py
If we have less than PCA_DIM (7) instances, the PCA will reduce the instance features to #instances and our code crashes because we assumed PCA_DIM. This PR fixes the problem.
=> FIX reduced features for the case if |Insts| < PCA_DIM

examples/branin/branin_scenario.txt, smac/epm/rf_with_instances.py, smac/intensification/intensification.py, smac/runhistory/runhistory.py, smac/smbo/smbo.py, smac/stats/stats.py, test/test_smbo/test_smbo.py
the title of the branch is a bit misleading. My main goal was to speed up the local search but I also changed other stuff to minimize the overhead of SMAC. Profiling SMAC on branin "with instances" (see aclib2), SMAC spends now more time in the subprocess than in its own functions (for the first 2000 function evaluations), even tough branin is such a cheap function.
* initialize local search with best configs from random search
* reduce number of trees in RF to 10 (as in SMAC2)
* run at least 2 configurations per intensify call (as in SMAC2)
* adaptively adjust number of local search iterations based on intensify stats
* more efficient runhistory data structure to get runs for a given
=> Minimize SMAC overhead

smac/facade/smac_facade.py, test/test_facade/test_smac_facade.py
Add a simple check to make sure that the objective function for SMAC and the target algorithm runner are identical.
=> MAINT add check for objective function

smac/smbo/acquisition.py, test/test_smbo/test_acquisition.py
=> MAINT use basic EI instead of EI which favours exploitation

smac/smbo/smbo.py, test/test_smbo/test_smbo.py
SMAC does not longer crash if the first run was a memout or a timout. More general, if an empty array X is passed to choose_next, a random set of configurations is returned.
Fixes issues #125 and #131.
=> Fix issues #125 and #131

smac/runhistory/runhistory.py, smac/tae/execute_ta_run.py, test/test_smbo/test_pSMAC.py
Implementing issue #81, adding human-readable mapping of StatusTypes. The originally wished for
\>\>\> print(mapping[status])
is realized through [Enum](https://docs.python.org/3/library/enum.html#enum.Enum) as
\>\>\> print(status.name)
JSON-serialization of runhistories is affected: status is now saved by customized JSON-Encoder.
This might affect the possibility of reading in the JSON-file from another language/without the object_hook.
=> CHANGE StatusType to Enum

smac/runhistory/runhistory.py, test/test_intensify/test_intensify.py, test/test_runhistory/test_runhistory.py, test/test_smbo/test_pSMAC.py
Fixes issue #167 by not changing the runhistory if a run with equal config, instance and seed would be added again.
=> FIX issue #167

smac/smbo/local_search.py, smac/smbo/smbo.py, test/test_runhistory/test_rfr_imputor.py
Instead of using a method for this, convert the configuration
into an array and replace missing values with -1.
=> Speed up conditional hyperparameter imputation

smac/configspace/__init__.py, smac/configspace/util.py, smac/runhistory/runhistory2epm.py, smac/smbo/local_search.py, smac/smbo/smbo.py, test/test_configspace/test_configspace.py, test/test_smbo/test_smbo.py
Refactor imputation into it's own function @mlindauer
=> MAINT refactor imputation of inactive hyperparameters into function

smac/utils/io/traj_logging.py, test/test_utils/io/test_traj_logging.py
Trajectory entries are named tuples, allowing access by name, e.g.: `tl.trajectory[n].train_perf'`
=> MAINT make trajectory entries named tuple (issue/#153)

smac/epm/uncorrelated_mo_rf_with_instances.py
Fixing issue/#94, UncorrelatedMultiObjectiveRandomForestWithInstances was the only class not derived from AbstractEPM.
=> MAINT make uncorrelated_mo_rf_with_inst subclass of AbstractEPM (issue/94)

smac/scenario/scenario.py, test/test_scenario/test_scenario.py
Setting par-factor to 1 by default if no factor is given. I.e. for `overall_obj` "mean" equals "mean1" equals "par" equals "par1".
=> Issue/#165 - setting par to 1 by default if no factor is given

examples/rf.py
Maintaining issue #90, removing the C++- implementation `pyrfr` from rf-example and replacing it with sklearn's `RandomForestRegressor`. Also updating the deprecated cross-validation-method and polish up the general appearance of the example.
Note that the execution now takes a little longer, since the C++-implementation was more efficient. As a consequence, the maximum number of function runs is reduced.
=> Issue/#90 replacing rf examples with sklearn-rf-implementation

smac/scenario/scenario.py, smac/smbo/smbo.py, test/test_smbo/test_smbo.py
Adding option intensification_percentage (analogous to SMAC2), must be in (0,1), defines the fraction of time assigned to intensification. Uses the `time_bound`-parameter in `intensifier.intensify`.
=> ADD intensification_percentage option

smac/scenario/scenario.py, test/test_scenario/test_scenario.py
Implementing issue/#201, enforcing verbosity on boolean arguments in scenario-files.
=> MAINT clarify truth-interpretation in scenario-options

smac/runhistory/runhistory.py, smac/scenario/scenario.py, smac/smbo/pSMAC.py, smac/smbo/smbo.py
* FIX update of runhistory wrt to capped runs in combination with shared_model
* MAINT add option in scenario to specify a list (or a glob expression) of dictionaries from which pSMAC should read the runhistories
=> MAINT pSMAC interface

smac/facade/smac_facade.py, smac/smac_cli.py, smac/smbo/pSMAC.py, test/test_smbo/test_pSMAC.py
Adds #204, always saves the runhistory at the end of an optimization run instead of only saving it when called from command line. As a side-effect, the filename of the runhistory as saved for pSMAC no longer has the SMAC seed in it's file name. This should anyway be no longer needed since @mlindauer implemented pSMAC loading data from different directories.
=> ADD #204, always save the runhistory

smac/runhistory/runhistory2epm.py
_build_matrix method in RunHistory2EPM4EIPS class calls 'impute_inactive_values' but this function is not imported. Replace by 'convert_configurations_to_array' call
=> FIX impute_inactive_values call in runhistory to epm for EIPS

smac/scenario/scenario.py
Add milliseconds to output directory name for scenario to avoid crash (OSError) when starting multiple smac instances in parallel (did happen on cluster)
=> Output directory name for scenario file

smac/epm/base_epm.py, smac/epm/random_epm.py, smac/epm/rf_with_instances.py, smac/epm/uncorrelated_mo_rf_with_instances.py, smac/facade/smac_facade.py, smac/scenario/scenario.py, test/test_epm/test_rfr_with_instances.py
* AbstractEPM handles PCA and marginalization over instances
* AbstractEPM can be seen as a wrapper around all other EPMs -- should make it easier to add other EPM models
* all instances of AbstractEPM have to call the inherited constructor
* remove a check in predict_marginalized_over_instances() since it is
not guarantueed that self.types is available
=> MAINT refactor EPM module

examples/rf.py
fixing issue/#223
- increase memory_limit to 3072 and runcount-limit to 200
- make example non-deterministic (since it actually is a randomized algorithm)
- use boston-housing-data from sklearn
- use cross-validation from sklearn
=> increase mem_limit for rf-example

smac/runhistory/runhistory.py
Inverting dict instead of parsing configurations again, fixing issue/#226.
=> MAINT make runhistorys load_json more efficient

smac/optimizer/smbo.py, test/test_smbo/test_smbo.py
This pull request is work in progress and and right now just a proof of concept. I'll add unit tests and documentation if the general ideas is approved.
Currently, the challengers are all created before calling the intensify function. As each second challenger is random, a lot of random samples are wasted creating this list of challengers. This PR replaces the ordinary python list by a custom list/iterator. Instead of holding a list of random configurations, it has all non-random configurations and a configuration sampler. In each second iteration, instead of returning the next element from the list of challengers, it samples a new random configuration.
On the RF example, this reduced the time to obtain a new list of challengers from 0.0181 to 0.0121 seconds (improvement of ~30%).
=> obtain random samples for intensification from a generator

smac/epm/rf_with_instances.py, test/test_epm/test_rfr_with_instances.py, test/test_runhistory/test_runhistory2epm.py
Apparently, a lot of features which were so far passed to the random forest options object need to be passed to a tree options object. This PR does the necessary changes. Furthermore, as having only 1000 nodes per tree only allows to model ~3000 distinct values, I increased the number to ~1M nodes per tree. Please keep in mind that there was no limit at all so far.
=> Fix forest options

smac/scenario/scenario.py, test/test_intensify/test_intensify.py, test/test_runhistory/test_runhistory2epm.py, test/test_scenario/test_scenario.py, test/test_tae/test_exec_func.py, test/test_tae/test_exec_tae_run.py, test/test_tae/test_tae_aclib.py, test/test_tae/test_tae_old.py, test/test_utils/io/test_traj_logging.py
Fixing issue #52, making run_obj mandatory and cutoff_time mandatory if run_obj is runtime.
=> Issue #52 make run_obj mandatory

smac/facade/smac_facade.py, smac/runhistory/runhistory2epm.py
FIX consider crashed runs for qual scenarios since cost_for_crash avail
* ADD one further debug output to get some feedback runhistory2epm
=> FIX consider crashed runs for qual scenarios since cost_for_crash avail

smac/scenario/scenario.py, smac/utils/io/input_reader.py, test/test_files/features_example.csv, test/test_files/train_insts_example.txt, test/test_scenario/test_scenario.py, test/test_utils/io/test_inputreader.py
This PR strips whitespaces and \n-ewlines from the feature-names in the input-reader.
Does anyone object to saving feature names in scenario-object as `scenario.feature_names`?
=> Feat names

changelog.md, requirements.txt, smac/__version__.py
Necessary to safely release a new version of the ConfigSpace which is not backwards compatible.
=> Make sure that installed ConfigSpace version is <0.4

smac/epm/uncorrelated_mo_rf_with_instances.py, test/test_epm/test_uncorrelated_mo_rf_with_instances.py
It appears that the previous implementation expected the `BaseEPM` and the `RandomForestWithInstances` to accept the same arguments. This is apparently wrong and fixed in this PR.
=> fix bug in uncorrelated_mo_rf_with_instances, improve tests

smac/optimizer/smbo.py, test/test_smbo/test_smbo.py
As the sampling for random configuration is about 10 times faster (at least for Auto-sklearn) with the latest ConfigSpace, increasing this number should be a safe thing to do.
=> Increase number of random configs for EI optimization

smac/facade/smac_facade.py, smac/scenario/scenario.py, smac/smac_cli.py, smac/stats/stats.py, test/test_cli/test_restore_state.py, test/test_scenario/test_scenario.py
Finally fixing issue #240.
Quoting from issue:
> We introduce a flat folder hierarchy. If the user does not specifie otherwise a SMAC experiment will have the following structure:
> 
> smac_<date>/run_<run_id>/*.json
> 
> The user can specify a output directory, e.g. ./myExperiment or ./myExperiment/ which results in:
> 
> ./myExperiment/run_<run_id>/*.json
> 
> If smac is about to write to an already existing directory, smac will move the folder (without checking whether other processes still use that folder):
> 
> ./myExperiment/run_<run_id>/*.json -> ./myExperiment/run_<run_id>.OLD/*.json
> 
> if run_<run_id>.OLD already exists, then another .OLD is appended (run_<run_id>.OLD.OLD)
Minor changes:
- stats now only saved if output-dir available
- restore-state now two functions (because …
=> new output structure

smac/optimizer/acquisition.py, smac/optimizer/ei_optimization.py, smac/optimizer/epils.py, smac/runhistory/runhistory.py, test/test_smbo/test/traj_old.csv, test/test_smbo/test_acquisition.py, test/test_smbo/test_ei_optimization.py
Instead of accepting a numpy array, the acquisition function is now
called with a list of configurations, giving the user more flexibility
what to do with that in the acquisition function calculation.
=> Generalize acquisition function

smac/facade/epils_facade.py, smac/facade/roar_facade.py, smac/facade/smac_facade.py, smac/optimizer/epils.py, smac/optimizer/smbo.py, smac/scenario/scenario.py, smac/smac_cli.py, smac/stats/stats.py, smac/utils/io/output_directory.py, smac/utils/io/output_writer.py, test/test_cli/test_restore_state.py, test/test_facade/test_smac_facade.py, test/test_scenario/test_scenario.py
Currently, the `run_id` needs to be passed to the scenario object. This PR removes this necessity. I would like to have this feature to pass a scenario dict to the user in Auto-sklearn and allow the user to create the scenario object from this, without having to deal with extra arguments.
=> Do not pass run_id to scenario file

.travis.yml, README.md, circle.yml, doc/faq.rst, doc/installation.rst
I know, it's failing right now, but I got the tests for python3.5 and python3.6 running again. I don't know how to get 3.4 running with Anaconda, though. Therefore, I propose to drop python3.4 support/testing and move on.
@KEggensperger @mlindauer @AndreBiedenkapp 
If you agree, I will remove python3.4 from the tests.
Here's a blog post explaining the changes: https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/
=> travis-ci: install different compilers

.travis.yml, Makefile, doc/faq.rst, requirements.txt, smac/facade/smac_facade.py, test/test_cli/test_restore_state.py, test/test_intensify/test_intensify.py, test/test_runhistory/test_rfr_imputor.py, test/test_tae/test_exec_func.py, test/test_utils/test_validate.py
* Add Makefile with `test`, `test-fast`, `test-runtimes`, `clean`, `clean-data` and `doc` targets.
* Fix rst files and docstrings which sphinx reported errors/warnings on.
* Print revision being tested on travis.
* Add 'slow' attribute on test cases slower than 1s.
=> Issue #373: Add Makefile

smac/facade/func_facade.py, test/test_facade/test_func_facade.py
Fixes issue #367 by padding zeros to parameter name such that sort returns correct order
=> FIX #367 add zeros to parameter names

smac/facade/func_facade.py, smac/optimizer/smbo.py, test/test_facade/test_smac_facade.py
Pretty simple, it removes the time limit functionality from `func_facade`, and instead adds `intensification_percentage` as a scenario argument.
Fixes #376.
Can be confirmed by running
```python
import numpy as np
from smac.configspace import ConfigurationSpace
from ConfigSpace.hyperparameters import UniformFloatHyperparameter
from smac.scenario.scenario import Scenario
from smac.facade.smac_facade import SMAC
from smac.facade.func_facade import fmin_smac
def rosenbrock_2d(x):
x1 = x['x1']
x2 = x['x2']
val = 100. * (x2 - x1 ** 2.) ** 2. + (1 - x1) ** 2.
return val
def rosenbrock_2d_array(x):
return rosenbrock_2d({'x1': x[0], 'x2': x[1]})
fixture = 6
for i in range(20):
np.random.seed(3)
cs = ConfigurationSpace()
cs.add_hyperparameter(
UniformFloatHyperparameter("x1", -5, 5, …
```
=> FIX #376, make fmin_smac deterministic

smac/utils/io/output_writer.py, smac/utils/io/traj_logging.py, test/test_utils/io/test_traj_logging.py
regarding issue #405, I think it makes sense to provide the user with more information about `OSError`s. I found different behaviours throughout SMAC, is this one good? Mainly, do you think `sys.exit` or simply reraising `OSError`s would be more appropriate?
=> MAINT improve oserror-message/traceback

examples/rosenbrock.py, smac/facade/smac_facade.py, test/test_facade/test_smac_facade.py, test/test_smbo/test_smbo.py
Finally fixes #209. In case an rng is provided, run_id is sampled from it unless provided.
=> Improve rng and run_id handling

smac/facade/smac_facade.py, smac/optimizer/smbo.py, smac/tae/execute_func.py, smac/tae/execute_ta_run.py, test/test_smbo/test_smbo.py, test/test_tae/test_exec_tae_run.py
Fix #410, add `abort-on-first-run-crash` argument to tae, so that initial design is not interrupted.
=> MAINT move abort-on-first-run-crash to tae

smac/optimizer/pSMAC.py
Because of our new output directory structure, the usage of pSMAC was unintuitive. The PR will also try to parse all subfolders with the syntax "run_*" such that users only have to provide the output directory of smac (which includes e.g., "run_1")
=> FIX pSMAC input dir parsing (regarding new output dir structure)

smac/utils/io/output_writer.py
Writing the cs in pcs can fail if not all parameter values of cat parameter are strings. The json format can deal with it. Therefore, I added a catch and try block to prevent SMAC from crashing.
=> FIX catch writing of pcs

smac/utils/io/cmd_reader.py
I switched to the development version of SMAC since I started using AutoFolio. I noticed that my computing cluster started cancelling jobs because of time limits. For some reason, SMAC had set my 'wallclock_limit' time to 'algo_runs_timelimit' without me specifying the 'use_ta_time' argument.
I think this was the cause, as the standard value for 'use_ta_time' ((str) False) was sent to the argparser and interpreted as (Bool)True.
=> parser argument use_ta_time type to 'truthy'

README.md, doc/faq.rst
Slightly modifies the FAQ to point to our contribution guide (link will only work if merged to master) and provide information for contributing code.
=> update doc to point to contribution guide

smac/utils/io/cmd_reader.py, smac/utils/io/output_writer.py, test/test_scenario/test_scenario.py
Fixing #478, always write pcs as json when writing scenario. If it was in pcs-format before, we write the json additionally to the pcs-format and set the path in the scenario to the json-file. Generally, both get written if possible.
=> Issue 478 json pcs

smac/utils/io/cmd_reader.py, smac/utils/io/input_reader.py, test/test_utils/io/test_inputreader.py
Fix #489, add input_reader support for `pcs_new` and `json`.
Also, add tests.
=> FIX #489 reading in pcs_new and json with input_reader

smac/epm/base_epm.py, smac/epm/rf_with_instances.py, smac/optimizer/ei_optimization.py, smac/runhistory/runhistory2epm.py, smac/utils/constants.py, test/test_epm/test_rf_with_instances.py
by reshuffling the for loop for computing the mean performance.
=> MAINT speed up rf predictions for log transformed data

smac/epm/rf_with_instances.py, smac/facade/smac_hpo_facade.py, smac/optimizer/ei_optimization.py, test/test_smbo/test_ei_optimization.py, test/test_smbo/test_smbo.py
Local search now starts from:
* the `num_points` observed configurations with the highest EI
* the `num_points` observed configurations with the lowest cost
* the `num_points` unobserved configurations with the highest EI, configurations obtained by random search
To account for the increased necessary computation (because of the up to three fold increase of initial points), we reduce the number of local searches from 100 to 10.
=> Change local search starting points

ci_scripts/run_unittests.sh, smac/facade/experimental/psmac_facade.py, test/test_facade/test_psmac_facade.py
This PR
* replaces multiprocessing by joblib to easily obtain the stdout and stderr as well as the return value of the parallelized function
* uses pseudo-parallelism for the unit test
=> Fix combination of travis-ci with numpy 1.17

smac/epm/gaussian_process_mcmc.py, test/test_epm/test_gp_mcmc.py
This PR unifies the normalization of y values for GPMCMC. y values are now normalized only on the level of the base class instead of sometimes by sklearn and sometimes by the GPML/GPMAP class (which implement different ways of normalizing the data).
=> Fix GPMCMC normalization of y values

smac/epm/gp_base_prior.py, test/test_epm/test_gp_priors.py
To avoid SMAC behaving in a random manner if forgetting to seed these objects.
=> Remove default rng from gp prior objects

smac/initial_design/initial_design.py, test/test_initial_design/test_initial_design.py
This might be advantageous in cases where one does meta-learning and wants to ensure that exactly 2 or 3 configurations are used to start.
=> Add argument to directly control the size of the initial design

smac/optimizer/acquisition.py, smac/optimizer/smbo.py, test/test_smbo/test_acquisition.py
Changes SMAC to:
* only update the acquisition function with attributes that are already present. This allows to update the acquisition function with costly arguments such as `X`, the whole training data, without the fear of it being stored in an ordinary acquisition function.
* Pass `X`, the incumbent configuration and the incumbent configuration in array format to the acquisition function.
* More unit tests for the acquisition function.
Reason:
This allows to implement acquisition functions which needs to know not only the incumbent value, but also the incumbent configuration, or even all data which was already evaluated.
=> Pass more data to the acquisition function

smac/utils/io/traj_logging.py, test/test_utils/io/test_traj_logging.py
Fix #488 by introducing `alljson` format for trajectory read and write.
Also, add interpretation of non-string categorical values in hyperparameters, such as `CategoricalHyperparameter` with `choices = [1, False, 'random_string]` to address issues such as https://github.com/automl/ParameterImportance/issues/107.
=> Issue 488 save incumbent in traj as json

smac/facade/roar_facade.py
This allows me to pass the recent fixed set acquisition function optimizer (#558) to the ROAR facade.
=> Add acquisition function optimizer args to ROAR facade

Makefile, examples/SMAC4HPO_rf.py, examples/SMAC4HPO_sgd_hyperband_instances.py, examples/spear_qcp/SMAC4AC_spear_qcp.py, examples/spear_qcp/scenario.txt, smac/facade/experimental/epils_facade.py, smac/facade/smac_ac_facade.py, smac/initial_design/default_configuration_design.py, smac/initial_design/factorial_design.py, smac/initial_design/initial_design.py, smac/initial_design/latin_hypercube_design.py, smac/initial_design/random_configuration_design.py, smac/initial_design/sobol_design.py, smac/intensification/abstract_racer.py, smac/intensification/hyperband.py, smac/intensification/intensification.py, smac/intensification/successive_halving.py, smac/optimizer/epils.py, smac/optimizer/epm_configuration_chooser.py, smac/optimizer/smbo.py, smac/runhistory/runhistory.py, test/test_facade/test_smac_facade.py, test/test_initial_design/test_initial_design.py, test/test_intensify/test_abstract_intensifier.py, test/test_intensify/test_hyperband.py, test/test_intensify/test_intensify.py, test/test_intensify/test_successive_halving.py, test/test_smbo/test_epils.py, test/test_smbo/test_epm_configuration_chooser.py, test/test_smbo/test_smbo.py
The basic design of the pull architecture for sampling challengers on-the-fly.
* Implemented by passing the optimizer (SMBO) as an argument to `intensify()` method
* Currently supports sending both a list of challengers and optimizer as arguments to the intensifier, since `InitialDesign` sends its own configurations for intensification.
**UPDATE**
* `InitialDesign` only returns the configurations to run and all runs happen only through the main BO loop in SMBO. This is to avoid sampling additional configurations (and redundant code) during initial design. 
~**Note**: Testcases have not been modified yet.~
=> Pull architecture (v0)

smac/facade/smac_bo_facade.py, smac/facade/smac_hpo_facade.py, smac/initial_design/initial_design.py, test/test_facade/test_smac4bo_facade.py, test/test_facade/test_smac4hpo_facade.py, test/test_initial_design/test_sobol_design.py
The Sobol Sequence implementation we're using fails with more than 40 dimensions. This PR adds
* a unit test for this
* a change to the SMAC4HPO facade to replace the sobol grid if there are too many hyperparameters.
=> Fix#513 - improve handling of sobol sequence for large search spaces

smac/intensification/successive_halving.py, smac/optimizer/smbo.py, test/test_smbo/test_smbo.py
* Fixed `FirstRunCrashedException` not raising an error when `abort_on_first_crash=True`
* Warning when successive halving/hyperband is used for a non-deterministic algorithm but `n_seeds=1`
=> first run crashed exception in smbo, warning in successive halving

smac/intensification/successive_halving.py, smac/tae/execute_func.py, test/test_intensify/test_successive_halving.py
There was an issue with running adaptive capping with successive halving because capped configurations were being considered when selecting for the next stage. Now they are ignored.
=> Fix capping issue in successive halving

smac/runhistory/runhistory.py, test/test_runhistory/test_runhistory.py, test/test_utils/test_validate.py
I recently faced a weird bug where the configurations in the runhistory are `None`, but which I can't easily debug. This PR will prevent adding `None` to the runhistory and will help me debugging this issue if the bug pops up again.
=> Stricter checks for things added to runhistory

smac/intensification/successive_halving.py, test/test_intensify/test_successive_halving.py
This bug was because of incomplete handling of the capped/failed challengers between stage changes. I've fixed it now and also added a test case for the same.
This would fix the failing spear_qcp example in development.
=> fix bug in adaptive capping of successive halving

smac/intensification/intensification.py, test/test_intensify/test_intensify.py
Intensification now evaluates the 1st incumbent twice, just like previous versions of SMAC
=> revert intensification behaviour for first configuration

ci_scripts/run_examples.sh, examples/spear_qcp/run.sh, examples/spear_qcp/run_ROAR.sh, examples/spear_qcp/run_SMAC.sh, smac/facade/roar_facade.py
The RandomEPM used in ROAR always predicts value ~0. If the actual values are much higher, imputation will fail as the predicted values are much below the lower threshold. Using log transformation for this case brings the values closer to zero and imputation will work.
=> FIX ROAR facade for AC

smac/intensification/successive_halving.py
The issue was with having multiple instances in the same stage, some successful and some failed. 
We ignore a configuration even if it was capped once. (reverting to the behaviour before refactoring)
=> fix capping issue in successive halving, again

smac/optimizer/ei_optimization.py, smac/runhistory/runhistory.py, test/test_smbo/test_ei_optimization.py, test/test_smbo/test_epm_configuration_chooser.py
by creating a callback which is only triggered if a non-random configuration is necessary. This does not yet prevent SMAC from constructing unnecessary models.
=> Evaluate acquisition function only if necessary

smac/intensification/intensification.py, smac/intensification/successive_halving.py, smac/optimizer/epm_configuration_chooser.py, smac/runhistory/runhistory2epm.py, test/test_intensify/test_successive_halving.py, test/test_smbo/test_epm_configuration_chooser.py
Update the behavior of the new DONOTADVANCE state. Configurations are first sorted by their performance when deciding which configurations to advance to the next budget. If a configuration with state DONOTADVANCE ends up in the higher budget, it is not executed any more. This can reduce the number of configurations to be executed in higher budgets to save time.
CC @KEggensperger @ashraaghav
=> Change behavior of donotadvance

smac/intensification/intensification.py, smac/runhistory/runhistory.py, test/test_intensify/test_intensify.py
Fixes an infinite loop in intensification which could occur if the acquisition function would always return the same configuration and no random configurations were used. The fix is to only end intensify if there are either no challengers left or one challenger was executed (and therefore the model would change for the next iteration).
=> Fix infinite loop

smac/facade/smac_bo_facade.py
Fixes a bug in the Bayesian optimization facade related to retrieving the number of dimensions based on the type array. This had to be changed because we changed the type of the type array quite a bit.
=> Fix type retrieval bug in BO facade

smac/epm/gaussian_process_mcmc.py, smac/facade/smac_bo_facade.py, test/test_epm/test_gp_mcmc.py
This PR fixes issue #665. More specifically, it:
* fixes a wrong assertion in the BOFacade
* uses the final result of the walker ensemble from emcee instead of a single chain (this mistake happened while updating the code to the latest version of emcee).
* adds an additional check that the number of walkers is correct
=> Fix issue #665; BO facade and GPMCMC samples

smac/facade/smac_ac_facade.py, smac/intensification/abstract_racer.py, smac/intensification/hyperband.py, smac/intensification/intensification.py, smac/intensification/successive_halving.py, smac/optimizer/smbo.py, smac/runhistory/runhistory.py, smac/tae/execute_func.py, smac/tae/execute_ta_run.py, smac/tae/execute_ta_run_wrapper.py, smac/utils/validate.py, test/test_facade/test_smac_facade.py, test/test_initial_design/test_initial_design.py, test/test_intensify/test_abstract_racer.py, test/test_intensify/test_eval_utils.py, test/test_intensify/test_hyperband.py, test/test_intensify/test_intensify.py, test/test_intensify/test_successive_halving.py, test/test_smbo/test_smbo.py, test/test_tae/test_exec_tae_run.py
Separated evaluation from get next challengers in intensification.
Created an object called runinfo that contains the necessary information for an isolated run.
The intensifier is now a state machine with the main stages given by (also in old code):
RUN_FIRST_CONFIG = 0  # to replicate the old initial design
RUN_INCUMBENT = 1  # Lines 3-7
RUN_CHALLENGER = 2  # Lines 8-17
RUN_BASIS = 3
and substrates given by (new):
self.challenger_same_as_incumbent = False
self.no_available_insts = False
self.to_run_empty = False
Readjusted the test to have the same functionality. Verified also via examples executing the same line of code using a profiler. Fundamentally, this change can be seen as a reordering such that:
- Eval challenger code was mostly moved to get challengers to be able to obtain the …
=> Separated next challenger form eval

.travis.yml, README.md, doc/index.rst, requirements.txt, setup.py, smac/__init__.py, smac/optimizer/smbo.py, test/test_smbo/test_epm_configuration_chooser.py
I believe the PR name says it all - will be helpful for Auto-sklearn
This PR drop Python 3.5 as the latest ConfigSpace version doesn't support it any more.
=> Add config_id to configuration objects prior to execution

smac/tae/__init__.py
The `BudgetExhaustedException` and `CappedRunException` are no longer used and can confuse developers.
=> Drop unused exceptions

smac/tae/dask_runner.py, test/test_tae/test_parallel_runner.py
Previously, the dask client passed to SMAC would be closed by SMAC. This test ensures that the same dask client can be used multiple times.
=> Allow reuse of dask clients

smac/intensification/intensification.py, smac/intensification/simple_intensifier.py, smac/intensification/successive_halving.py, smac/runhistory/runhistory.py, smac/tae/execute_func.py, test/test_runhistory/test_runhistory.py, test/test_tae/test_exec_func.py
This PR moves a check that entries in the runhistory can be serialized from the TAE for functions to the runhistory class. This has two advantages:
1. All TAEs profit from this check
2. A try/except around the current check prevented it from making SMAC fail and show the error message. Instead, SMAC would fail when serializing the runhistory at the end of the optimization.
=> Improve runhistory type checks

smac/intensification/simple_intensifier.py, smac/optimizer/smbo.py, test/test_intensify/test_simple_intensifier.py, test/test_smbo/test_smbo.py
Check if workers are idle, and only then launch jobs in the case of the simple intensifier.
=> Only suggest jobs if workers available

smac/intensification/successive_halving.py, test/test_intensify/test_successive_halving.py
Problem Statement:
When running in parallel, the current development code has problem tracking the number of instances per configuration. That is, there is no real per-config tracking of what instances have been launched and which one finished -- per configuration.
This causes an error of the form:
```
ValueError: Cannot compare configs that were run on different instances-seeds-budgets: [InstSeedBudgetKey(instance='75193_10MIN_logloss', seed=0, budget=0.0), InstSeedBudgetKey(instance='189909_10MIN_logloss', seed=0, budget=0.0)] vs [InstSeedBudgetKey(instance='189909_10MIN_logloss', seed=0, budget=0.0)]
```
Where an instance 75193_10MIN_logloss was never launched, because the code failed to notice this run was not launched for this config. 
Solution:
Track per configuration what instances …
=> Moved to internal registration of instances per config

requirements.txt, smac/initial_design/sobol_design.py
Fixes this issue: #729 
But now scipy needs to be  >= 1.7.0 --> Update requirements?
=> Fix sobol sequence #729

extras_require.json, smac/initial_design/latin_hypercube_design.py
The two perform roughly equivalent using five seeds. Dropping pyDOE reduces our requirement count by one:
```
Bohachevsky    Branin  Camelback  Forrester  GoldsteinPrice  Hartmann3  Hartmann6   Levy1D    Levy2D  Rosenbrock2D  Rosenbrock5D    SinOne    SinTwo   Average      Rank
lhd_new    -0.453092 -3.067249  -1.457917  -6.368932        1.344273  -4.960274  -1.188263 -6.29473 -0.831744      0.387343      3.273479 -6.564149 -2.164840 -2.180469  1.384615
default    -0.526523 -3.098636  -1.433102  -6.357172        1.523234  -4.785882  -1.017738 -5.71695 -1.752664      0.504228      3.018586 -6.208062 -2.483468 -2.179550  1.615385
```
=> Replace pydoe by scipy's lhd

extras_require.json, smac/__init__.py, smac/epm/base_gp.py, smac/epm/gaussian_process.py, smac/epm/gaussian_process_mcmc.py, smac/epm/gp_kernels.py, test/test_epm/test_gp.py
This PR stops using scikit-optimize and instead uses the raw scikit-learn GP. I checked the performance on a bunch of test functions using 5 repetitions and the numbers are favorable:
```
Bohachevsky    Branin  Camelback  Forrester  GoldsteinPrice  Hartmann3  Hartmann6    Levy1D    Levy2D  Rosenbrock2D  Rosenbrock5D    SinOne    SinTwo   Average      Rank
skopt      -0.739422 -3.775036  -1.666626  -5.694597        1.089118  -5.007008  -0.600312 -6.614990 -1.097518      0.542982      3.371725 -6.648250 -2.264304 -2.238788  1.692308
sklearn    -0.652663 -5.012642  -1.667781  -7.306148        1.089118  -5.375514  -0.600312 -6.908985 -1.097518      0.542982      3.371725 -6.996612 -2.264304 -2.529127  1.307692
```
=> Drop scikit-optimize dependency

changelog.md, smac/__init__.py, test/test_initial_design/test_factorical_design.py, test/test_initial_design/test_initial_design.py
Updates from `0.13.2dev` to `0.13.2`, filling in the changelog.
=> Version bump 0.13.2dev -> 0.14.0

smac/configspace/__init__.py, smac/optimizer/ei_optimization.py
The iterator returned by `ConfigSpace.util.get_one_exchange_neighborhood` may visit an invalid configuration. If it does so, it either raises a `ValueError` (with the probability 0.05) or yields the configuration (otherwise). This pull request ensures that `LocalSearch._do_search` handles these situations gracefully.
1. If `ValueError` is raised, it is caught and ignored (instead of crashing `smac`).
2. If an invalid configuration is visited and scores better than the current candidate, it is ignored (instead of replacing the current candidate).
The script `run.sh` in [demo.zip](https://github.com/automl/SMAC3/files/7156367/demo.zip) demonstrates raising of `ValueError` from the iterator. The error is raised with a probability greater than 0 and smaller than 1.
Issue at ConfigSpace that …
=> Handle invalid neighbors in local search gracefully

smac/tae/dask_runner.py
Doing some unfortunate debugging of one of our examples in `auto-sklearn` and came across [this piece of documentation](http://distributed.dask.org/en/stable/client.html#pure-functions-by-default). Essentially `pure=True` just means `dask` won't recompute `f` given the same input `x`. It's unlikely that we ever have the same input `x` but in the of chance we do, it won't give the same result do to time, randomness in some algorithms etc...
Unlikely to change anything but seems more correct to include `pure=False`.
> By default, distributed assumes that all functions are pure. Pure functions:
>  - always return the same output for a given set of inputs
>  - do not have side effects, like modifying global state or creating files
> If this is not the case, you should use the pure=False …
=> Specfiy to dask that runs shouldn't cache results

changelog.md, smac/runhistory/runhistory.py, test/test_runhistory/test_runhistory.py
Add some dunder methods to `RunHistory` so it acts a little bit more like a [`Mapping`](https://docs.python.org/3/library/collections.abc.html).
```python
rh = RunHistory()
... populate it somehow
keys = list(rh)
values = list(rh.values())
for runkey, runvalue in rh.items():
...
if runkey in rh:
...
runvalue = rh[runkey]
unpacked = {**rh}
if len(rh) > 0:
"""This is more pythonic than defining an `empty` method as it does,
but i don't want to break anything so empty can stay in"""
...
```
Note:
I wanted to make it a `MutableMapping` which lets you add things into the dictionary with the normal `dictionary[key] = value` syntax, but the class is pretty heavily designed against it due to it's `add` method not taking RunValues but rather all the individual components. I tried using the `_add` …
=> Add Mapping type to Runhistory

changelog.md, smac/facade/roar_facade.py
**[minor breaking change, see note below when making release notes]**
The `ROAR(SMAC4AC)` facade had a default `run_id = 1` while `SMAC4AC` has it as `run_id = None`. This caused issues with respect to assumed paths in autosklearn when passing a different SMAC facade as we relied on the behaviour to be similar to `SMAC4AC`.
Edit:
Turns out it was a bad test setup in autosklearn which is easily fixable on my end. Still though, I think it's worth fixing this.
Looking through the code, I couldn't find any reason why `ROAR` should set it explicitly to `1` while it's super should be `None`.
It's possible someone out there relied on this behaviour, this should probably be mentioned as a minor breaking change in release notes.
I also updated the type signatures to match for `run_id` and `rng`.
> …
=> [Bug Fix] Fixes the signature of ROAR to match it's parent SMAC4AC

changelog.md, examples/python/plot_simple_multi_objective.py, smac/facade/smac_ac_facade.py, smac/intensification/abstract_racer.py, smac/intensification/hyperband.py, smac/intensification/intensification.py, smac/intensification/parallel_scheduling.py, smac/intensification/simple_intensifier.py, smac/intensification/successive_halving.py, smac/optimizer/multi_objective/abstract_multi_objective_algorithm.py, smac/optimizer/multi_objective/aggregation_strategy.py, smac/optimizer/multi_objective/parego.py, smac/runhistory/runhistory.py, smac/runhistory/runhistory2epm.py, smac/utils/multi_objective.py, tests/test_multi_objective/test_schaffer.py, tests/test_runhistory/test_runhistory_multi_objective.py, tests/test_utils/test_multi_objective.py
Closes #852.
I slightly rearranged the runhistory so that it's more intuitive.
What else did I do?
`average_cost/min_cost/sum_cost` return a list of floats (instead of a float) now.
For example, for `average_cost`, each objective is averaged separately. Imagine you have two runs with [100, 200] and [0, 0] then you'd get [50, 100]. However, once you call `get_cost`, this (cached) [50, 100] is normalized based on all passed entries. That means that `get_cost` returns a float in the end. 
> Unfortunately, the intensifier and also some other methods work with `average_cost` or `sum_cost` (which should actually be a private method). So, I have to call `normalize_cost` in the intensifier again. Since `_cost_per_config`(cache for `average_cost`) is always storing the current state with all …
=> Fix Multi-Objective cache

CHANGELOG.md, smac/initial_design/abstract_initial_design.py
This PR fixes a bug in which integer hyperparameters would not be created correctly in the initial design. This went unnoticed, except in the case where it was part of a condition and the function deactivate_inactive_hyperparameters was called.
This PR fixes this bug by mapping the random float that was sampled by, for example and LHD or Sobol sequence, to the float representation of an integer by calling _transform and _inverse_transform of the integer hyperparameter.
=> Fix 531 correctly create integers in initial design

.github/workflows/stale_reminder.yml
Adds an action that sends a reminder mail for soon-to-be stale and old issues. Relevant secrets have already been added to the repo.
=> Add stale reminder email action

CHANGELOG.md, smac/scenario.py
Solves #927
This problem should not happen in the first place because the scenario should accept strings as feature names only. However, this makes SMAC more robust and user-friendly.
=> Transform integer feature names to strings

smac/main/smbo.py, smac/runhistory/runhistory.py
[Auto-sklearn](https://github.com/automl/auto-sklearn) is heavily dependent on SMAC. I'm currently trying to bump up our dependency to the latest version of SMAC.
Auto-sklearn used to rely on the fact that SMAC set the [config_id attribute](https://github.com/automl/ConfigSpace/blob/1d93d98e4b0b73a0d3a6799f05f11f4c1a4bb5f9/ConfigSpace/configuration_space.pyx#L1651) of a sampled Configuration object before the `submit_trial()` method was called on the function runner object in the [main optimization loop](https://github.com/automl/SMAC3/blob/731854e8effe72d76cb07636458e783143f32dc5/smac/main/smbo.py#L272-L319).
This functionality got removed since 2.0, and now the config_ids of the sampled Configurations are all None.
Is there any good reason why you got rid of it?
If there isn't, then …
=> fix(runhistory): set id of the sampled config

.github/dependabot.yml
Just makes dependabot target development with it's changes. This should prevent divergences between `main` and `development`. I set myself as the reviewer and assignee of these. Please let me know if anyone else want's to be notified and specifically assigned to these.
=> ci: set dependabot to development

.github/workflows/pre-commit-update.yml, CHANGELOG.md, smac/facade/abstract_facade.py
Allow a user to disable SMAC from setting up its own custom logging by passing `logging_level=False`. This change is backwards compatible and does not change any existing behaviours.
Please see issue #948
=> feat: Option preventing SMAC setting up logging

CHANGELOG.md, smac/intensifier/abstract_intensifier.py
Fixes #956 , by first computing the union and intersection of the incumbents and then taking the difference.
=> Compute the actual differences between the isb keys.

.github/workflows/stale_reminder.yml
Runs the job on Mondays instead of Wednesdays.
=> Adjust schedule for stale reminder

smac/__init__.py, smac/facade/abstract_facade.py, smac/utils/logging.py
Prevent SMAC doing automatic logging setup at import, in general it's very bad practice for libraries to automatically perform computation at import time as simply `import smac` performs unknown changes to a users environemnt.
* Closes #948
=> fix(logging): Prevent automatic logging setup at init

CHANGELOG.md, smac/intensifier/abstract_intensifier.py, smac/main/smbo.py
Previously, if no seed was given, the seed 0 was used.
=> Fix validate method of SMAC to use the seed given in the scenario

CHANGELOG.md, smac/intensifier/hyperband.py, smac/intensifier/successive_halving.py, tests/test_intensifier/test_hyperband.py
Addresses issue #977 by choosing the original paper *algorithm* (not the example table) as the implementation for the bracket scaling. Thank you @AlexandreAbraham for reporting this on the (not maintained anymore) BOHB repository.
=> Adjust hyperband configuration distribution across brackets

setup.py
It seems like the CLI was removed at some point but the entry points are still there.
Ref: https://github.com/search?q=repo%3Aautoml%2FSMAC3%20cmd_line_call&type=code
=> Remove leftover CLI entry points

CHANGELOG.md, smac/facade/abstract_facade.py
When `data_to_scatter={}`, it causes an error in Dask, so I fixed this error.
=> Raise an error for invalid scatter data

smac/utils/configspace.py
Previously this would only show keys present in the challenger and not in the incumbent. Also by using string `[key]` indexing instead of `.get(key)`, there could be a `KeyError` if the `key` was not present in the `Configuration`.
* Closes #1041
=> fix(configspace): shows all keys in print

CHANGELOG.md, smac/main/smbo.py
Did not preserve callback order by adding to the index -1. Now appends to the callback list if index is None.
See this example:
Before:
```python
In [1]: cbs = ["U", "W", "S"]
...: l = []
...: print(cbs)
...: for cb in cbs:
...:     l.insert(-1, cb)
...:     print(cb, l)
...: 
['U', 'W', 'S']
U ['U']
W ['W', 'U']
S ['W', 'S', 'U']
```
Now:
```python
In [2]: cbs = ["U", "W", "S"]
...: l = []
...: print(cbs)
...: for cb in cbs:
...:     l.insert(len(l), cb)
...:     print(cb, l)
...: 
['U', 'W', 'S']
U ['U']
W ['U', 'W']
S ['U', 'W', 'S']
```
=> Fix callback order

smac/main/config_selector.py
I had an error here `l:276`, `NoneType` is not comparable with `float`
https://github.com/automl/SMAC3/blob/e64e1918eeb88e93f9f201ece343624fb2943e9d/smac/main/config_selector.py#L269-L276
The previous version was expecting `available_budget` to be `list[float] | list[None]` but it was possible to get `list[float | None]` as `TrialKey.budget: float | None`. When this happen, it would cause the later `sorted` to fail
Essentially for some reason I had `None` and a `float` value in `available_budgets` (most likely due to warmstarting). I'm not sure where the root issue is but we can circumvent it with this.
The previous version should have caught this potential error with mypy but didn't.
The reason this problem didn't show up was due to the `# type: ignore` which would have correctly warned …
=> Fix(config_selector): Budget checking

smac/runner/target_function_runner.py
When encoding the smac instance to disk, part of that process is to use the `__code__` attribute of a function to essentially *hash* it to disk, allowing SMAC to detect if the function has changed between invocations.
However when using a `partial`, these do not have a `__code__` attribute, moreover, they can have extra variables attached to them, as per the reason you would use a `partial`.
This PR fixes this and makes sure that even the arguments used in the `partial` are considered when using `overwrite=False`, and SMAC attempts to restart from it's last state on disk.
=> Fix: target runner with partial func

CHANGELOG.md, examples/2_multi_fidelity/1_mlp_epochs.py, examples/2_multi_fidelity/2_sgd_datasets.py, examples/3_multi_objective/2_parego.py, tests/fixtures/models.py
- Handle configspace as dictionary in mlp and parego example
- Adapt sgd loss to newest scikit-learn version ("log" not accepted anymore")
=> Handle configspace as dictionary in mlp example

CHANGELOG.md, smac/model/random_forest/abstract_random_forest.py, tests/test_model/test_rf.py
`OrdinalHyperparameter`is missing for random forest imputer (as this type of hp is allowed by SMAC's configuration space constructor: https://github.com/automl/SMAC3/blob/main/smac/utils/configspace.py#L72)
An additional message is raised to make the Value error more concrete.
=> allow rf to impute OrdinalHyperparameter

CHANGELOG.md, smac/intensifier/abstract_intensifier.py, tests/test_intensifier/test_abstract_intensifier.py
Fixes #1068 to make sure newly evaluated configs are rejected in case they are worse than the existing incumbent.
=> Fix config rejection for #1068

CHANGELOG.md, smac/facade/hyperparameter_optimization_facade.py
The random seed specified in the Scenario, is propagated to most other places, but not the default ProbabilityRandomDesign child component.
This is part of an effort to track down some sources of non-determinism.
=> Propagate the Scenario random seed to get_random_design

CHANGELOG.md, examples/4_advanced_optimizer/4_intensify_crossvalidation.py
Closes #1056
I hope the example explains itself. There are two things that I would have loved to add, but that currently do not work (will create separate issues for them):
1. A comparison against requiring all folds evaluated (option for this is missing from the intensifier).
2. ~~Removing the warning that instance features are missing (SMAC currently gives an error when passing instance features).~~ This now works after upgrading the pyrfr package.
=> [#1056] Add example on intensify for cross-validation.

tests/test_runhistory/test_runhistory_encoder.py
When testing the [new ConfigSpace branch](https://github.com/automl/ConfigSpace/tree/typing-cython-3) to check if it would break anything in SMAC, this test failed just due to a change on randomization.
I've fixed the test to not rely on the randomization of sampling.
=> test: Fix upper bounds for `test_transformer()` and no random in `test_transformer_conditional()`

docs/advanced_usage/9_parallelism.rst, examples/1_basics/7_parallelization_cluster.py, setup.py, smac/facade/abstract_facade.py
revert #1023 since this seems no longer to be an issue with the latest daskqueue. Additionally, we add some more descriptions to show how to restrict the resources  for parallelization jobs.
=> Revert 1023

CHANGELOG.md, smac/main/smbo.py, smac/runhistory/dataclasses.py, smac/runhistory/runhistory.py, smac/runner/abstract_runner.py, smac/runner/dask_runner.py, smac/runner/target_function_runner.py, smac/runner/target_function_script_runner.py, tests/test_runner/test_script_target_algorithm_runner.py, tests/test_runner/test_target_algorithm_runner.py
Changed the TrialValue to hold CPU time and have SMBO use this value to calculate its budgets
- Same behaviour as the original 'time' variable, except in its calculation tries to estimate CPU time with process_time instead.
- Added in to TrialValue object, RunHistory and SMBO so it can be recorded and correctly calculate the remaining CPU budget
Pytest are passing (on my machine)
=> Adding in CPU time to wherever time is defined as variable "cpu_time"

docs/3_getting_started.md, docs/advanced_usage/8_logging.md
Output of runhistory not well documented, related: #1174 
(First step to update docs, then code bc changing code has downstream consequences of libs like DeepCAVE)
Closes #1085
=> 1085 runhistory documentation

CHANGELOG.md, setup.py, smac/acquisition/maximizer/differential_evolution.py
From the version change of scipy's `1.14.x` to `1.15.x` `DifferentialEvolution` now takes `rng` instead of `seed`.
In the code, check the signature and pass the kwarg accordingly. This should allow backwards compatibility with earlier python versions.
=> Fix kwargs for DifferentialEvolution

CHANGELOG.md, examples/1_basics/6_priors.py, smac/acquisition/function/prior_acquisition_function.py, tests/test_acquisition/test_functions.py
Im this MR I will adapt the PriorAcquisitionFunction.
This contains fixes for #1076
=> Fix PriorAcquisitionFunction
