test/test_facade/test_smac_facade.py
This unittest checks that when passing a target algorithm object to the SMAC class, that the SMAC class actually injects a stats object.
=> ADD unittest for issue #48

README.md, doc/conf.py, doc/manual.rst
Changed the Theme for the documentation.
Minor additions to the spear-qcp example
=> Change Theme of the documentation

examples/leadingones.py, examples/rf.py, examples/rosenbrock.py, smac/facade/func_facade.py, smac/facade/smac_facade.py, smac/tae/execute_func.py, test/test_facade/test_func_facade.py, test/test_facade/test_roar_facade.py, test/test_facade/test_smac_facade.py, test/test_smbo/test_smbo.py, test/test_tae/test_exec_func.py
=> ADD first draft of scipy.optimize.fmin_l_bfgs_b-like interface

smac/runhistory/runhistory.py, smac/smbo/smbo.py, test/test_smbo/test_smbo.py
Perform local search on configurations from previous runs as it is described in the SMAC paper.
=> Perform local search on configurations from previous runs

.landscape.yml
Adds a landscape configuration file. Checks are now with python3 but also with increased strictness and enforcing full pep8. Thus, the score stays the same.
=> add landscape conf

smac/intensification/intensification.py, test/test_intensify/test_intensify.py
=> FIX compare_configs by using explicit set semantic

smac/intensification/intensification.py
To make it a bit clearer what the arguments do...
=> DOC improve intensification argument documentation

smac/facade/func_facade.py, smac/facade/smac_facade.py, smac/runhistory/runhistory2epm.py, test/test_runhistory/test_runhistory2epm.py
@sfalkner requested an interface to get all X,y from SMAC
* ADD X,y interface
* change return values of `fmin_smac` to return also the smac object which allows to use other convenience function
=> ADD convenient function to get X,y of RH

smac/facade/func_facade.py, smac/scenario/scenario.py, test/test_scenario/test_scenario.py
=> MAINT instances are casted to str

.travis.yml
Use codecov instead of coverage
=> FIX 205; ADD codecov

smac/facade/smac_facade.py, smac/smbo/acquisition.py, test/test_smbo/test_acquisition.py, test/test_smbo/test_smbo.py
* ADD logEI (according to Hutter et al. LION'11)
* RM derivative argument in acq methods
* MAINT some cleanup in acquisition.py
=> ADD logEI (according to Hutter et al. LION'11)

smac/runhistory/runhistory2epm.py, smac/smac_cli.py
* adapt logging format depending on logging level
* add output in the beginning of rh2epm
* running pep8 tool on smac_cli.py
=> MAINT output format

smac/runhistory/runhistory.py, smac/tae/execute_ta_run.py
Move EnumEncoder from runhistory.save to runhistory as requested in issue #219.
=> Issue #219 make EnumEncoder accessible

requirements.txt, smac/runhistory/runhistory2epm.py, smac/tae/execute_ta_run_aclib.py, smac/tae/execute_ta_run_old.py, smac/utils/io/output_writer.py, smac/utils/io/traj_logging.py
With this PR we would switch to the latest pcs format. I added ordinal hyperparameter values, but other than that I could not find anything that does not work using some quick checks and writing simple pcs files.
This PR can be merged as soon as the ConfigSpace is updated on pypi and we agree that it works for our optimization problems.
=> Issue/#268 Switch to new pcs format

test/test_runhistory/test_runhistory2epm.py
Fixing issue #312 by changing unit-test-value.
=> FIX unit-test with new pyrfr

doc/installation.rst, doc/options.rst, smac/scenario/scenario.py
Fixing issue #310 and a typo in the installation-docs.
=> fix Issue/#310 rendering of scenario options

smac/optimizer/ei_optimization.py, smac/runhistory/runhistory.py
to be at most as many runs as there are points to start
from in the runhistory.
=> Bound number of local search runs

smac/facade/roar_facade.py
which was not passed to SMAC so far.
=> FIX ROAR run id

README.md, doc/index.rst
fixing broken link. also, @mfeurer do we drop 3.4? (i remember reading something like that, we might as well update the docs(?))
=> FIX broken link in readme

.travis.yml, scripts/test_no_files_left.sh, smac/facade/smac_facade.py, test/test_cli/test_restore_state.py, test/test_facade/test_func_facade.py, test/test_facade/test_smac_facade.py, test/test_scenario/test_scenario.py, test/test_smbo/test_smbo.py, test/test_utils/test_validate.py
Delete generated test data in unit tests, added bash script that checks if test cases leave any files (looks if git's directory contains any untracked files) and call it in travis.
=> Issue 351: Add test to make sure that our unit tests do not leave any files

scripts/smac-validate.py, smac/utils/validate.py, test/test_utils/test_validate.py
=> FIX validation failure without instance features

smac/facade/func_facade.py
=> ADD **kwargs in fmin facade passed to SMAC facade

smac/utils/validate.py, test/test_utils/test_validate.py
When reusing runhistories, validation didn't reevaluate runs that were capped, crashed or aborted.
Fixed that, see added test-case for explanation.
=> FIX validation of capped runs

smac/configspace/__init__.py, smac/utils/io/output_writer.py
=> Save configspace also as json

test/test_utils/test_validate.py
fix #390 
@mfeurer can you confirm, that this fixes the issue?
=> Issue 390 tests validation fail wrong dir

doc/apidoc/smac.facade.epils_facade.rst, doc/apidoc/smac.facade.rst, doc/apidoc/smac.optimizer.epils.rst, doc/apidoc/smac.optimizer.random_configuration_chooser.rst, doc/apidoc/smac.optimizer.rst, doc/apidoc/smac.utils.io.output_directory.rst, doc/apidoc/smac.utils.io.rst, doc/apidoc/smac.utils.logging.rst, doc/apidoc/smac.utils.rst, doc/apidoc/smac.utils.validate.rst, doc/index.rst, doc/manual.rst, doc/quickstart.rst, doc/validation.rst, scripts/smac-validate.py, smac/utils/io/traj_logging.py, smac/utils/validate.py, test/test_utils/test_validate.py
=> ADD validation docs

smac/facade/smac_facade.py
#285 final output is incumbent configuration and now also value is logged.
=> ADD value to final output

smac/__init__.py
Just adding ".dev" to __version__.
=> ADD ".dev" to version

smac/initial_design/initial_design.py, smac/initial_design/latin_hypercube_design.py, smac/initial_design/sobol_design.py
Change LHD design such that it can handle categorical, ordinal and constant parameters
=> MAINT extend lhd to non-continuous params

smac/facade/bogp_facade.py, smac/optimizer/smbo.py, smac/runhistory/runhistory2epm.py, test/test_runhistory/test_runhistory2epm.py
So far the scaling was only done for the log transformation. This PR adds scaling to each runhistory and calls a standard function on the runhistory when retrieving the incumbent value.
=> FIX perform scaling for each runhistory2epm

smac/epm/base_epm.py
I think the args-order is mixed up in this error message.
=> FIX error msg args order

doc/index.rst, doc/usage_recomendation.rst
=> Add a table to describe different use cases for our facades

ci_scripts/create_doc.sh
by swapping the api docs building the actual building of the documentation.
=> Try fixing the API docs

smac/optimizer/ei_optimization.py, test/test_smbo/test_ei_optimization.py, test/test_smbo/test_smbo.py
This PR vectorizes the local search.
=> Vectorize local search

smac/epm/base_epm.py
As far as I can see, the Error-Arguments are swapped here.
=> Fix epm error msg

changelog.md, smac/__init__.py
I (and @mlindauer) think it's time for a new release.
=> Prepare new release

smac/epm/gaussian_process_mcmc.py, smac/facade/smac_bo_facade.py
by using the hyperparameters suggested by https://arxiv.org/pdf/1908.06674.pdf
This also removes unnecessary print statements.
=> update Gaussian process hyperparameters

test/test_epm/test_gp_mcmc.py
Can be merged once the tests pass
=> FIX unittests

smac/facade/experimental/epils_facade.py, smac/facade/roar_facade.py, smac/facade/smac_ac_facade.py, smac/initial_design/initial_design.py, smac/intensification/abstract_intensifier.py, smac/intensification/abstract_racer.py, smac/intensification/hyperband.py, smac/intensification/intensification.py, smac/intensification/successive_halving.py, smac/optimizer/epils.py, smac/optimizer/smbo.py, test/test_intensify/test_abstract_intensifier.py, test/test_intensify/test_intensify.py, test/test_intensify/test_successive_halving.py
* Added a common base class for intensifier & successive halving
* Updated function definitions to use the base intensifier instead of SMAC's intensification 
The default intensifier is still SMAC's intensify procedure and used whenever the intensifier is None.
=> Base class for intensifier

smac/epm/gaussian_process.py, test/test_epm/test_gp.py
* improve GP sample shape for different y shapes
* add unit test for different shapes of y for the Gaussian process
=> improve GP sample shape for different y shapes

smac/optimizer/ei_optimization.py
Simplified version of https://github.com/automl/SMAC3/commit/5f1374f274d38da4cb79fe6bfd621d69a0a9bfc5
Not sure how to unit test this, though.
=> Add list of configs EI maximizer

smac/facade/roar_facade.py, smac/facade/smac_bo_facade.py
* add additional arguments to roar facade
* allow passing None to BO facade
=> Extend facades

setup.py
This pull request should fix encoding errors in the authors' names.
=> Fix encoding error in author names

ci_scripts/run_flake8.sh, examples/SMAC4BO_rosenbrock.py, examples/SMAC4HPO_acq_rosenbrock.py, examples/SMAC4HPO_mlp_hyperband.py, examples/SMAC4HPO_rf.py, examples/SMAC4HPO_rosenbrock.py, examples/SMAC4HPO_sgd_hyperband_instances.py, examples/SMAC4HPO_svm.py, examples/branin/branin.py, examples/branin/branin_fmin.py, examples/branin/cmdline_wrapper.py, examples/branin/restore_state.py, examples/fmin_rosenbrock.py, examples/spear_qcp/SMAC4AC_spear_qcp.py, scripts/plot_traj_perf.py, scripts/smac, scripts/smac-validate.py
More pep8 goodness.
Fixed issues for scripts and examples
=> Pep8 the second

ci_scripts/run_mypy.sh, smac/epm/base_epm.py, smac/epm/base_gp.py, smac/epm/base_imputor.py, smac/epm/base_rf.py, smac/epm/gaussian_process.py, smac/epm/gaussian_process_mcmc.py, smac/epm/gp_base_prior.py, smac/epm/gp_kernels.py, smac/epm/random_epm.py, smac/epm/rf_with_instances.py, smac/epm/rfr_imputator.py, smac/epm/uncorrelated_mo_rf_with_instances.py, smac/epm/util_funcs.py, smac/facade/smac_bo_facade.py, smac/facade/smac_hpo_facade.py, smac/utils/duplicate_filter_logging.py, test/test_epm/test_gp_priors.py, test/test_facade/test_smac_facade.py
This PR adds type annotations to the epm subpackage. Furthermore, mypy checks of the epm subpackage are now triggered on every commit. The checks are not as strict as possible, but I wanted to get this started at all, and we can make the tests stricter over time.
More annotations of other subpackages to come...
=> Add type annotations for mypy, part 1

smac/epm/rf_with_instances.py
Speeding up the rf predictions marginalized over instances
=> MAINT improve prediction speed of rf_with_instances

changelog.md, smac/__init__.py
* bump version number
* update changelog
=> prepare release of version 0.12.1

requirements.txt, smac/initial_design/sobol_design.py, smac/runhistory/runhistory.py, smac/tae/execute_ta_run.py, smac/utils/validate.py, test/test_cli/test_deterministic_smac.py, test/test_initial_design/test_sobol_design.py, test/test_runhistory/test_runhistory.py, test/test_smbo/test_pSMAC.py
* Add timestamps to be stored in runhistory
* Migrated sobol initial design to scipy's implementation
=> Fix issues #647 and #600 (partially)

changelog.md
Improve changelog with feedback from #667.
=> Improve 0.12.3 changelog

examples/parallel_sh_mlp.py, smac/intensification/hyperband.py, smac/intensification/parallel_hyperband.py, smac/intensification/parallel_scheduling.py, test/test_intensify/test_parallel_hyperband.py, test/test_intensify/test_parallel_scheduler.py
This commit enables a new parallel hyperband intensifier and it's proper checking
=> Initial commit parallel HB

smac/optimizer/smbo.py, smac/stats/stats.py, smac/utils/io/traj_logging.py, smac/utils/validate.py, test/test_cli/test_restore_state.py, test/test_intensify/test_eval_utils.py, test/test_intensify/test_hyperband.py, test/test_intensify/test_intensify.py, test/test_intensify/test_successive_halving.py, test/test_smbo/test_smbo.py, test/test_tae/test_exec_tae_run.py, test/test_utils/io/test_traj_logging.py
This PR splits the stats attribute `ta_runs` into `ta_runs_submitted` and `ta_runs_finished` to correctly keep track of both.
=> Parallel bookkeeping

smac/tae/base.py, test/test_tae/test_parallel_runner.py
Add a check to make sure we log in crashes in additional info
=> Additional info logs in crashes 

smac/optimizer/smbo.py, smac/tae/execute_func.py, test/test_smbo/test_smbo.py, test/test_tae/test_parallel_runner.py
* in case of first run crashed
* in case of the pynisher crashing
=> Add better error messages

smac/facade/smac_bohb_facade.py, smac/intensification/hyperband.py, smac/intensification/successive_halving.py, test/test_intensify/test_hyperband.py, test/test_intensify/test_successive_halving.py
Fixes #701 
Additionally, allows to use SH w/ the BOHB facade
=> Fix initial hb budget

doc/api.rst, smac/callbacks.py, smac/facade/smac_ac_facade.py, smac/optimizer/smbo.py, test/test_facade/test_smac_facade.py, test/test_smbo/test_smbo.py
* allow registering callbacks with the SMAC facade
* implements a callback for _incorporate_run_results
=> Add callback mechanism

smac/facade/smac_ac_facade.py, test/test_facade/test_smac_facade.py
Pass memory limit to ExecuteTAFuncDict
=> FIX mem limit for pynisher

.github/workflows/pytest.yml, README.md, doc/index.rst, setup.py, smac/__init__.py, test/test_epm/test_rf_with_instances.py, test/test_smbo/test_smbo.py, test/test_tae/test_parallel_runner.py
=> Drops support for python 3.6

doc/quickstart.rst, examples/SMAC4HPO_svm.py
I hope everything is correct, this is my first pullrequest :D
=> Documentation changes reflecting #544

.github/workflows/docs.yml, docs/pages/getting_started/index.rst, docs/pages/getting_started/installation.rst, docs/pages/getting_started/package_overview.rst, docs/pages/glossary.rst, docs/themes/smac/static/css/custom.css, extras_require.json, requirements.txt, test/test_epm/test_gp_mcmc.py
=> update installation doc

examples/python/synthetic_function.py, smac/__init__.py, smac/utils/dependencies.py
remove redundant dependencies checks
=> Docs installation

smac/acquisition_optimizer/__init__.py, smac/acquisition_optimizer/differential_evolution.py, smac/acquisition_optimizer/local_and_random_search.py, smac/acquisition_optimizer/local_search.py, smac/acquisition_optimizer/random_search.py, smac/chooser/__init__.py, smac/chooser/boing_chooser.py, smac/chooser/turbo_chooser.py, smac/utils/subspaces/boing_subspace.py
This PR aims at redesigning the interfaces to decouple different modules. Still under developing.
=> simplify the maximizer's interface

CHANGELOG.md, smac/facade/abstract_facade.py, smac/main/smbo.py
=> Fix callback order

docs/6_references.rst
=> fix broken references

CHANGELOG.md, smac/facade/abstract_facade.py, smac/intensifier/abstract_intensifier.py, smac/runner/target_function_runner.py
And can better set memory limits (specify number and unit) for pynisher.
=> Pipe dask_client through facade for exec on hpc

examples/4_advanced_optimizer/3_metadata_callback.py, setup.py, tests/fixtures/scenario.py, tests/test_initial_design/test_initial_design.py
We do not need botorch/torch requirements anymore.
* Closes #1004
=> Drop torch requirements

smac/model/gaussian_process/kernels/base_kernels.py, smac/runhistory/runhistory.py, smac/utils/multi_objective.py
* Closes #1042
Should basically always use:
* `isinstance` for type checking values
* `issubclass` for type checking types
* `np.issubdtype` for type checking dtypes
=> fix: dtypes

CHANGELOG.md, docs/3_getting_started.rst, setup.py, smac/model/random_forest/random_forest.py, smac/runhistory/encoder/abstract_encoder.py
New(er) numpy does not support np.NaN anymore + restrict numpy and ConfigSpace versions
=> Fix dependencies (numpy + ConfigSpace) and docs

CHANGELOG.md, smac/intensifier/intensifier.py, smac/intensifier/successive_halving.py
Addresses https://github.com/automl/SMAC3/issues/960
=> Add information on handling of stopIteration error

setup.py, smac/utils/numpyencoder.py
Allow numpy >= 2.x
Closes #1144
=> Update numpy dependency

CHANGELOG.md, smac/acquisition/maximizer/local_search.py
=> Add LocalSearch Fix

README.md
Added link for SEO, feel free to move somewhere else in the readme
=> Add AutoML space link

smac/facade/abstract_facade.py
=> Fixed log output in case more workers have been configured than available.
